name: doro_gear
description: "PC Gear shop."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.0
  uuid: ^4.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/products.json
    - assets/images/
    - assets/lang/
